# Actividad
Introducción a la convolución



---
Por: Ángela Daniela Córdoba Álvarez


---




####**¿Qué es?**
La convolución es una operación matemática usada en el procesamiento de señales e imágenes.  

En el primero sirve para aplicar filtros a una señal con el fin de resaltar ciertas características o realizar ciertas operaciones; además, implica multiplicar dos funciones (la señal de entrada y el kernel del filtro)e integrar el producto resultante en un intervalo específico (el kernel del filtro es la función de respuesta al impulso que especifica cómo debe modificarse la señal de entrada).

**Ejemplo:** Sea una señal de entrada $x(t)$ y un filtro con respuesta al impulso $h(t)$. Luego, la señal de la entrada con el filtro es $y(t)=x(t)\cdot h(t)=\int_{-\infty}^{\infty} x(\tau) \cdot h(t-\tau) d\tau$, donde:
> * $x(t)$ es la señal de entrada
> * $h(t)$ es la respuesta al impulso del filtro
> * $y(t)$ es la señal de salida resultante
> * $\tau$ es una variable de integración

Esta convolución se utiliza para aplicar filtros y realizar diversas operaciones en las señales, lo que permite resaltar, suavizar o modificar ciertas características de interés.



---


### Ejemplo númerico: Convolución 1D a mano
Sea $x[n]=[2,1,0,1,2]$ y $h[n]=[1,-1]$.

Luego, con la fórmula de convolución discreta obtenemos: $\sum_{k=-∞}^{∞}x[k]\cdot h[n-k]$, en donde desplazaremos $h[n]$ a lo largo de $x[n]$ y multiplicaremos elemento por elemento para luego sumarlo los productos resultantes.

Entonces,

* Con $h[n]$ al inicio y $n=0$:

$y[0]=(2\cdot 1)+(1\cdot -1)+(0\cdot 0)+(1\cdot 0)+(2\cdot 0)=1$

* Desplazando $h[n]$ una posición a la derecha y $n=1$:

$y[1]=(2\cdot 0)+(1\cdot 1)+(0\cdot -1)+(1\cdot 0)+(2\cdot 0)=1$

* Luego, desplazando $h[n]$ otra posición a la derecha y $n=2$:

$y[2]=(2\cdot 0)+(1\cdot 0)+(0\cdot 1)+(1\cdot -1)+(2\cdot 0)=-1$

* Con $n=3$:

$y[3]=(2\cdot 0)+(1\cdot 0)+(0\cdot 0)+(1\cdot 1)+(2\cdot -1)=-1$

* Por tanto, el resultado de convolucionar la señal de entrada con el filtro (usando convolución discreta en una dimensión) es $y[n]=[-1,-1,1,1]$.

### Convolución 1D

In [ ]:
import numpy as np

# Definir las señales de entrada y el filtro
x = np.array([2, 1, 0, 1, 2]) # Señal de entrada
h = np.array([1, -1]) # Filtro

# Aplicar la convolución
y = np.convolve(x, h, mode='valid') # Valores de la convolución donde las señales se superponen (sin relleno)

# Imprimir el resultado
print("Señal de salida después de la convolución:")
print(y)

Señal de salida después de la convolución:
[-1 -1  1  1]


En el segundo sirve para aplicar filtros o máscaras a una imagen para resaltar ciertas características o realizar ciertas operaciones: suavizado (reducir el ruido), realce de bordes (destacar contornos), detección de patrones, etc.

La convolución, en este caso, implica superponer una ventana de tamaño específico (kernel o máscara) en cada píxel de la imagen y luego realizar una operación de suma ponderada. Dicho resultado se asigna al píxel central de la ventana y esto genera una nueva imagen convolucionada.

La operación de convolución se hace calculando la suma ponderada de los elementos de la imagen de entrada bajo la ventana del kernel. La fórmula es: $I'(x,y)=\sum_{i}\sum_{j}I(x+i,y+j)\cdot K(i,j)$, donde:
> * $I'(x,y)$ es el valor resultante en el punto (x,y) de la imagen convolucionada
> * $I(x+i,y+j)$ son los valores de los píxeles vecinos de la imagen de entrada (I) bajo la ventana del kernel (K)
> * $K(i,j)$ son los valores del kernel



---
### Ejemplo numérico de convolución 2D discreto

Sea la matriz de entrada $\begin{bmatrix}1 & 2 & 3 & 3\\ 4 & 5 & 6 & 6\\ 7 & 8 & 9 & 9\\ 7 & 8 & 9 & 9 \end{bmatrix}$ y el filtro $\begin{bmatrix}0 & 1 & 0\\ -1 & 1 & -1\\ 0 & 1 & 0\end{bmatrix}$.


Luego, se coloca el filtro sobre la matriz de entrada y se multiplica elemento por elemento para luego sumar los resultados, lo cual se repite para cada ubicación posible del filtro en la matriz de entrada.


### Convolución 2D discreto

In [ ]:
import numpy as np
from scipy.signal import convolve2d

# Definir la matriz de entrada (señal) y el kernel
input_matrix = np.array([[1, 2, 3, 3],
                         [4, 5, 6, 6],
                         [7, 8, 9, 9],
                         [7, 8, 9, 9]])
kernel = np.array([[0,  1,  0],
                   [-1, 1, -1],
                   [0,  1,  0]])

# Aplicar la convolución 2D
# Se realiza la convolución en regiones donde el kernel y la entrada coinciden completamente
output_matrix = convolve2d(input_matrix, kernel, mode='valid')

# Imprimir el resultado
print("Matriz de salida después de la convolución:")
print(output_matrix)

# Imprimir el resultado sin mode
output_matrix_ = convolve2d(input_matrix, kernel)
print("Matriz de salida después de la convolución sin mode:")
print(output_matrix_)

Matriz de salida después de la convolución:
[[5 7]
 [5 7]]
Matriz de salida después de la convolución sin mode:
[[ 0  1  2  3  3  0]
 [-1  3  3  4  6 -3]
 [-4  7  5  7 12 -6]
 [-7 10  5  7 15 -9]
 [-7  6  0  1  9 -9]
 [ 0  7  8  9  9  0]]
